the journey of ml starts from here

lemme load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/Global_Cybersecurity_Threats_2015-2024.csv")

In [10]:
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [16]:
#methoud 1 of phase 1 o feature 1.3.4 
X =df[[
    "Country",
    "Year",
    "Attack Type",
    "Target Industry",
    "Number of Affected Users",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used",
    "Incident Resolution Time (in Hours)"
]]
Y = df["Financial Loss (in Million $)"]

#methoud 2 
X = df.drop(columns=["Financial Loss (in Million $)"])

Y = df["Financial Loss (in Million $)"]

In [ ]:
#feature 1.6 1.5 is the defination segments missing value checking 
df.isnull().sum()

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

In [7]:
#feature 1.7 
df.duplicated().sum()

np.int64(0)

In [8]:
#feature 1.8 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   str
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   str
 3   Target Industry                      3000 non-null   str
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   int64
 7   Security Vulnerability Type          3000 non-null   str
 8   Defense Mechanism Used               3000 non-null   str
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(4), str(5)
memory usage: 234.5 KB

In [9]:
#phase 2 feature 2.5 
from sklearn.preprocessing import LabelEncoder

In [5]:
#converting to the label encoding 
le=LabelEncoder()
df['Attack Source']=le.fit_transform(df['Attack Source'])
df["Attack Source"].head(10)

0    0
1    0
2    0
3    2
4    1
5    3
6    1
7    3
8    3
9    0
Name: Attack Source, dtype: int64

In [6]:
df["Attack Source"].unique()#checkig them

array([0, 2, 1, 3])

In [ ]:
#phase 2 feature2.6 #one hot coding using pandas 
pd.get_dummies(df["Attack Type"])

       DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0     False    False              False      True       False          False
1     False    False              False     False        True          False
2     False    False               True     False       False          False
3     False    False              False     False        True          False
4     False    False               True     False       False          False
...     ...      ...                ...       ...         ...            ...
2995  False    False              False     False        True          False
2996  False    False              False     False       False           True
2997  False    False              False     False       False           True
2998  False    False              False     False       False           True
2999  False    False              False     False       False           True

[3000 rows x 6 columns]

In [12]:
attack_encoded=pd.get_dummies(df["Attack Type"])

In [13]:
attack_encoded.head()

    DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0  False    False              False      True       False          False
1  False    False              False     False        True          False
2  False    False               True     False       False          False
3  False    False              False     False        True          False
4  False    False               True     False       False          False

In [ ]:
#feature 2.9 
categorical_columns = [
    "Country",
    "Attack Type",
    "Target Industry",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used"
]

numerical_columns = [
    "Year",
    "Number of Affected Users",
    "Incident Resolution Time (in Hours)"
]

target = "Financial Loss (in Million $)"

In [26]:
#phase 3 tarin test split 
#feature 3.3.4.5.6.7

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(2400, 9)
(600, 9)
(2400,)
(600,)

In [ ]:
#feature 3.5