the journey of ml starts from here

lemme load the dataset

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("../data/Global_Cybersecurity_Threats_2015-2024.csv")

In [7]:
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [8]:
#methoud 1 of phase 1 o feature 1.3.4 
X =df[[
    "Country",
    "Year",
    "Attack Type",
    "Target Industry",
    "Number of Affected Users",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used",
    "Incident Resolution Time (in Hours)"
]]
Y = df["Financial Loss (in Million $)"]

#methoud 2 
X = df.drop(columns=["Financial Loss (in Million $)"])

Y = df["Financial Loss (in Million $)"]

In [9]:
#feature 1.6 1.5 is the defination segments missing value checking 
df.isnull().sum()

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

In [10]:
#feature 1.7 
df.duplicated().sum()

np.int64(0)

In [11]:
#feature 1.8 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   str
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   str
 3   Target Industry                      3000 non-null   str
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   str
 7   Security Vulnerability Type          3000 non-null   str
 8   Defense Mechanism Used               3000 non-null   str
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(3), str(6)
memory usage: 234.5 KB

In [12]:
#phase 2 feature 2.5 
from sklearn.preprocessing import LabelEncoder

In [13]:
#converting to the label encoding 
le=LabelEncoder()
df['Attack Source']=le.fit_transform(df['Attack Source'])
df["Attack Source"].head(10)

0    0
1    0
2    0
3    2
4    1
5    3
6    1
7    3
8    3
9    0
Name: Attack Source, dtype: int64

In [14]:
df["Attack Source"].unique()#checkig them

array([0, 2, 1, 3])

feature Enginnering and encoding phase 2

In [15]:
#phase 2 
# feature2.6 #one hot coding using pandas only for one coloumn 
pd.get_dummies(df["Attack Type"])

       DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0     False    False              False      True       False          False
1     False    False              False     False        True          False
2     False    False               True     False       False          False
3     False    False              False     False        True          False
4     False    False               True     False       False          False
...     ...      ...                ...       ...         ...            ...
2995  False    False              False     False        True          False
2996  False    False              False     False       False           True
2997  False    False              False     False       False           True
2998  False    False              False     False       False           True
2999  False    False              False     False       False           True

[3000 rows x 6 columns]

In [36]:
attack_encoded=pd.get_dummies(df["Attack Type"])

In [37]:
attack_encoded.head()

    DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0  False    False              False      True       False          False
1  False    False              False     False        True          False
2  False    False               True     False       False          False
3  False    False              False     False        True          False
4  False    False               True     False       False          False

In [38]:
#feature 2.9 
categorical_columns = [
    "Country",
    "Attack Type",
    "Target Industry",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used"
]

numerical_columns = [
    "Year",
    "Number of Affected Users",
    "Incident Resolution Time (in Hours)"
]

target = "Financial Loss (in Million $)"

Train test split phase 3

In [39]:
#phase 3 
#feature 3.3.4.5.6.7

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(2400, 39)
(600, 39)
(2400,)
(600,)

project preprocessing phase 4

In [40]:
X.select_dtypes(include="object").columns

Index([], dtype='str')

In [49]:
# Create X
X = df[[
    "Country",
    "Year",
    "Attack Type",
    "Target Industry",
    "Number of Affected Users",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used",
    "Incident Resolution Time (in Hours)"
]]

Y = df["Financial Loss (in Million $)"]

In [50]:
#coverting all the coloumns to the one hot coding 
X = pd.get_dummies(
    X,
    columns=[
        "Country",
        "Attack Type",
        "Target Industry",
        "Attack Source",
        "Security Vulnerability Type",
        "Defense Mechanism Used"
    ]
)

In [51]:
# THEN split
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [52]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Year                                            3000 non-null   int64
 1   Number of Affected Users                        3000 non-null   int64
 2   Incident Resolution Time (in Hours)             3000 non-null   int64
 3   Country_Australia                               3000 non-null   bool
 4   Country_Brazil                                  3000 non-null   bool
 5   Country_China                                   3000 non-null   bool
 6   Country_France                                  3000 non-null   bool
 7   Country_Germany                                 3000 non-null   bool
 8   Country_India                                   3000 non-null   bool
 9   Country_Japan                                   3000 non-null   bool
 10  Country_Russia                                  3000 non-null   bool
 11  Country_UK                                      3000 non-null   bool
 12  Country_USA                                     3000 non-null   bool
 13  Attack Type_DDoS                                3000 non-null   bool
 14  Attack Type_Malware                             3000 non-null   bool
 15  Attack Type_Man-in-the-Middle                   3000 non-null   bool
 16  Attack Type_Phishing                            3000 non-null   bool
 17  Attack Type_Ransomware                          3000 non-null   bool
 18  Attack Type_SQL Injection                       3000 non-null   bool
 19  Target Industry_Banking                         3000 non-null   bool
 20  Target Industry_Education                       3000 non-null   bool
 21  Target Industry_Government                      3000 non-null   bool
 22  Target Industry_Healthcare                      3000 non-null   bool
 23  Target Industry_IT                              3000 non-null   bool
 24  Target Industry_Retail                          3000 non-null   bool
 25  Target Industry_Telecommunications              3000 non-null   bool
 26  Attack Source_0                                 3000 non-null   bool
 27  Attack Source_1                                 3000 non-null   bool
 28  Attack Source_2                                 3000 non-null   bool
 29  Attack Source_3                                 3000 non-null   bool
 30  Security Vulnerability Type_Social Engineering  3000 non-null   bool
 31  Security Vulnerability Type_Unpatched Software  3000 non-null   bool
 32  Security Vulnerability Type_Weak Passwords      3000 non-null   bool
 33  Security Vulnerability Type_Zero-day            3000 non-null   bool
 34  Defense Mechanism Used_AI-based Detection       3000 non-null   bool
 35  Defense Mechanism Used_Antivirus                3000 non-null   bool
 36  Defense Mechanism Used_Encryption               3000 non-null   bool
 37  Defense Mechanism Used_Firewall                 3000 non-null   bool
 38  Defense Mechanism Used_VPN                      3000 non-null   bool
dtypes: bool(36), int64(3)
memory usage: 175.9 KB

feature scaling phase 5

In [54]:
#phase 5 #feature 5.1
#feature scaling 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [44]:
print(X_train_scaled[:5])

[[-0.8992088   0.16402194  1.14056027 -0.32712547 -0.33487441 -0.32556226
  -0.3341044   3.0496605  -0.35081295 -0.33641127 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867  2.19022863
  -0.44183608 -0.41595736 -0.40277488 -0.39364538 -0.41250563  2.27020839
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
  -0.56772709 -0.56965192 -0.5728597   1.66897842  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [-0.54784098 -1.59192434  0.16723026 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867  2.19022863
  -0.44183608 -0.41595736  2.48277649 -0.39364538 -0.41250563 -0.4404882
  -0.40137644 -0.39010813 -0.53881591 -0.58312392 -0.60302269  1.71113614
  -0.56772709  1.75545796 -0.5728597  -0.59916892 -0.48104129  1.94935887
  -0.50455324 -0.5        -0.50130175]
 [-1.60194443  1.05496647 -1.58476375 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619  2.27718401 -0.42008403 -0.46454867 -0.45657334
  -0.44183608 -0.41595736 -0.40277488 -0.39364538  2.42420932 -0.4404882
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
  -0.56772709 -0.56965192  1.74562812 -0.59916892  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [-0.8992088  -0.48121812 -0.41676774 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867 -0.45657334
   2.26328279 -0.41595736  2.48277649 -0.39364538 -0.41250563 -0.4404882
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
   1.76140969 -0.56965192 -0.5728597  -0.59916892  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [ 0.85763027  1.10579747 -0.02743574 -0.32712547 -0.33487441  3.07160912
  -0.3341044  -0.32790535 -0.35081295 -0.33641127 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403  2.15262696 -0.45657334
  -0.44183608 -0.41595736 -0.40277488 -0.39364538 -0.41250563 -0.4404882
  -0.40137644  2.56339188 -0.53881591  1.71490137 -0.60302269 -0.58440703
  -0.56772709 -0.56965192 -0.5728597   1.66897842 -0.48104129 -0.51298918
  -0.50455324  2.         -0.50130175]]

In [55]:
#feature5.2 

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

X_train_minmax = minmax.fit_transform(X_train)

X_test_minmax = minmax.transform(X_test)

In [56]:
print(X_train_minmax[:5])

[[0.22222222 0.55070629 0.83098592 0.         0.         0.
  0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         1.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         1.         1.         0.
  0.         0.         0.        ]
 [0.33333333 0.04233407 0.54929577 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         1.         0.         0.         0.         1.
  0.         0.         0.        ]
 [0.         0.8086478  0.04225352 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.         1.         0.         0.         0.
  0.         0.         1.         0.         1.         0.
  0.         0.         0.        ]
 [0.22222222 0.36389982 0.38028169 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  1.         0.         1.         0.         0.         0.
  0.         0.         1.         0.         0.         0.
  1.         0.         0.         0.         1.         0.
  0.         0.         0.        ]
 [0.77777778 0.82336412 0.49295775 0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.
  0.         1.         0.         1.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         1.         0.        ]]

In [ ]:
#phase 6 liner regresion 
#feature 6.8
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled,Y_train)
#THE MODEL HAS BEEN TRAINED

LinearRegression()

In [61]:
prediction = model.predict(X_test_scaled)

In [62]:
print(prediction[:5])

[51.29498768 47.31148304 48.18451622 54.96237136 52.29294352]

In [63]:
print(Y_test.iloc[:5])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
Name: Financial Loss (in Million $), dtype: float64

In [68]:
#model evaluation r^2 #feature 6.12 
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, prediction)
print(r2)

-0.006025665291256699

In [74]:
#feature6.13
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(Y_test, prediction)
mean_absolute_error(Y_test,prediction)
print(mae)

24.62073724385283

In [75]:
#feature 6.14 Mean Squared Error (MSE)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, prediction)
print(mse)

813.5061676892593

In [76]:
#feature 6.15 Root Mean Squared Error (RMSE)
import numpy as np
rmse = np.sqrt(mse)
print(rmse)

28.522029515608796