the journey of ml starts from here

lemme load the dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/Global_Cybersecurity_Threats_2015-2024.csv")

In [3]:
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [4]:
#methoud 1 of phase 1 o feature 1.3.4 
X =df[[
    "Country",
    "Year",
    "Attack Type",
    "Target Industry",
    "Number of Affected Users",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used",
    "Incident Resolution Time (in Hours)"
]]
Y = df["Financial Loss (in Million $)"]

#methoud 2 
X = df.drop(columns=["Financial Loss (in Million $)"])

Y = df["Financial Loss (in Million $)"]

In [5]:
#feature 1.6 1.5 is the defination segments missing value checking 
df.isnull().sum()

Country                                0
Year                                   0
Attack Type                            0
Target Industry                        0
Financial Loss (in Million $)          0
Number of Affected Users               0
Attack Source                          0
Security Vulnerability Type            0
Defense Mechanism Used                 0
Incident Resolution Time (in Hours)    0
dtype: int64

In [6]:
#feature 1.7 
df.duplicated().sum()

np.int64(0)

In [7]:
#feature 1.8 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 10 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Country                              3000 non-null   str
 1   Year                                 3000 non-null   int64
 2   Attack Type                          3000 non-null   str
 3   Target Industry                      3000 non-null   str
 4   Financial Loss (in Million $)        3000 non-null   float64
 5   Number of Affected Users             3000 non-null   int64
 6   Attack Source                        3000 non-null   str
 7   Security Vulnerability Type          3000 non-null   str
 8   Defense Mechanism Used               3000 non-null   str
 9   Incident Resolution Time (in Hours)  3000 non-null   int64
dtypes: float64(1), int64(3), str(6)
memory usage: 234.5 KB

In [8]:
#phase 2 feature 2.5 
from sklearn.preprocessing import LabelEncoder

In [9]:
#converting to the label encoding 
le=LabelEncoder()
df['Attack Source']=le.fit_transform(df['Attack Source'])
df["Attack Source"].head(10)

0    0
1    0
2    0
3    2
4    1
5    3
6    1
7    3
8    3
9    0
Name: Attack Source, dtype: int64

In [10]:
df["Attack Source"].unique()#checkig them

array([0, 2, 1, 3])

feature Enginnering and encoding phase 2

In [11]:
#phase 2 
# feature2.6 #one hot coding using pandas only for one coloumn 
pd.get_dummies(df["Attack Type"])

       DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0     False    False              False      True       False          False
1     False    False              False     False        True          False
2     False    False               True     False       False          False
3     False    False              False     False        True          False
4     False    False               True     False       False          False
...     ...      ...                ...       ...         ...            ...
2995  False    False              False     False        True          False
2996  False    False              False     False       False           True
2997  False    False              False     False       False           True
2998  False    False              False     False       False           True
2999  False    False              False     False       False           True

[3000 rows x 6 columns]

In [12]:
attack_encoded=pd.get_dummies(df["Attack Type"])

In [13]:
attack_encoded.head()

    DDoS  Malware  Man-in-the-Middle  Phishing  Ransomware  SQL Injection
0  False    False              False      True       False          False
1  False    False              False     False        True          False
2  False    False               True     False       False          False
3  False    False              False     False        True          False
4  False    False               True     False       False          False

In [14]:
#feature 2.9 
categorical_columns = [
    "Country",
    "Attack Type",
    "Target Industry",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used"
]

numerical_columns = [
    "Year",
    "Number of Affected Users",
    "Incident Resolution Time (in Hours)"
]

target = "Financial Loss (in Million $)"

Train test split phase 3

In [15]:
#phase 3 
#feature 3.3.4.5.6.7

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(2400, 9)
(600, 9)
(2400,)
(600,)

project preprocessing phase 4

In [16]:
X.select_dtypes(include="object").columns

/tmp/ipykernel_8574/2213039483.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns

Index(['Country', 'Attack Type', 'Target Industry', 'Attack Source',
       'Security Vulnerability Type', 'Defense Mechanism Used'],
      dtype='str')

In [17]:
# Create X
X = df[[
    "Country",
    "Year",
    "Attack Type",
    "Target Industry",
    "Number of Affected Users",
    "Attack Source",
    "Security Vulnerability Type",
    "Defense Mechanism Used",
    "Incident Resolution Time (in Hours)"
]]

Y = df["Financial Loss (in Million $)"]

In [18]:
#coverting all the coloumns to the one hot coding 
X = pd.get_dummies(
    X,
    columns=[
        "Country",
        "Attack Type",
        "Target Industry",
        "Attack Source",
        "Security Vulnerability Type",
        "Defense Mechanism Used"
    ]
)

In [19]:
# THEN split
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [20]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 39 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Year                                            3000 non-null   int64
 1   Number of Affected Users                        3000 non-null   int64
 2   Incident Resolution Time (in Hours)             3000 non-null   int64
 3   Country_Australia                               3000 non-null   bool
 4   Country_Brazil                                  3000 non-null   bool
 5   Country_China                                   3000 non-null   bool
 6   Country_France                                  3000 non-null   bool
 7   Country_Germany                                 3000 non-null   bool
 8   Country_India                                   3000 non-null   bool
 9   Country_Japan                                   3000 non-null   bool
 10  Country_Russia                                  3000 non-null   bool
 11  Country_UK                                      3000 non-null   bool
 12  Country_USA                                     3000 non-null   bool
 13  Attack Type_DDoS                                3000 non-null   bool
 14  Attack Type_Malware                             3000 non-null   bool
 15  Attack Type_Man-in-the-Middle                   3000 non-null   bool
 16  Attack Type_Phishing                            3000 non-null   bool
 17  Attack Type_Ransomware                          3000 non-null   bool
 18  Attack Type_SQL Injection                       3000 non-null   bool
 19  Target Industry_Banking                         3000 non-null   bool
 20  Target Industry_Education                       3000 non-null   bool
 21  Target Industry_Government                      3000 non-null   bool
 22  Target Industry_Healthcare                      3000 non-null   bool
 23  Target Industry_IT                              3000 non-null   bool
 24  Target Industry_Retail                          3000 non-null   bool
 25  Target Industry_Telecommunications              3000 non-null   bool
 26  Attack Source_0                                 3000 non-null   bool
 27  Attack Source_1                                 3000 non-null   bool
 28  Attack Source_2                                 3000 non-null   bool
 29  Attack Source_3                                 3000 non-null   bool
 30  Security Vulnerability Type_Social Engineering  3000 non-null   bool
 31  Security Vulnerability Type_Unpatched Software  3000 non-null   bool
 32  Security Vulnerability Type_Weak Passwords      3000 non-null   bool
 33  Security Vulnerability Type_Zero-day            3000 non-null   bool
 34  Defense Mechanism Used_AI-based Detection       3000 non-null   bool
 35  Defense Mechanism Used_Antivirus                3000 non-null   bool
 36  Defense Mechanism Used_Encryption               3000 non-null   bool
 37  Defense Mechanism Used_Firewall                 3000 non-null   bool
 38  Defense Mechanism Used_VPN                      3000 non-null   bool
dtypes: bool(36), int64(3)
memory usage: 175.9 KB

feature scaling phase 5

In [21]:
#phase 5 #feature 5.1
#feature scaling 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [22]:
print(X_train_scaled[:5])

[[-0.8992088   0.16402194  1.14056027 -0.32712547 -0.33487441 -0.32556226
  -0.3341044   3.0496605  -0.35081295 -0.33641127 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867  2.19022863
  -0.44183608 -0.41595736 -0.40277488 -0.39364538 -0.41250563  2.27020839
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
  -0.56772709 -0.56965192 -0.5728597   1.66897842  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [-0.54784098 -1.59192434  0.16723026 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867  2.19022863
  -0.44183608 -0.41595736  2.48277649 -0.39364538 -0.41250563 -0.4404882
  -0.40137644 -0.39010813 -0.53881591 -0.58312392 -0.60302269  1.71113614
  -0.56772709  1.75545796 -0.5728597  -0.59916892 -0.48104129  1.94935887
  -0.50455324 -0.5        -0.50130175]
 [-1.60194443  1.05496647 -1.58476375 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619  2.27718401 -0.42008403 -0.46454867 -0.45657334
  -0.44183608 -0.41595736 -0.40277488 -0.39364538  2.42420932 -0.4404882
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
  -0.56772709 -0.56965192  1.74562812 -0.59916892  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [-0.8992088  -0.48121812 -0.41676774 -0.32712547 -0.33487441 -0.32556226
  -0.3341044  -0.32790535 -0.35081295  2.97255203 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403 -0.46454867 -0.45657334
   2.26328279 -0.41595736  2.48277649 -0.39364538 -0.41250563 -0.4404882
  -0.40137644 -0.39010813  1.85592145 -0.58312392 -0.60302269 -0.58440703
   1.76140969 -0.56965192 -0.5728597  -0.59916892  2.07882365 -0.51298918
  -0.50455324 -0.5        -0.50130175]
 [ 0.85763027  1.10579747 -0.02743574 -0.32712547 -0.33487441  3.07160912
  -0.3341044  -0.32790535 -0.35081295 -0.33641127 -0.32399441 -0.34175797
  -0.33023825 -0.46056619 -0.43913886 -0.42008403  2.15262696 -0.45657334
  -0.44183608 -0.41595736 -0.40277488 -0.39364538 -0.41250563 -0.4404882
  -0.40137644  2.56339188 -0.53881591  1.71490137 -0.60302269 -0.58440703
  -0.56772709 -0.56965192 -0.5728597   1.66897842 -0.48104129 -0.51298918
  -0.50455324  2.         -0.50130175]]

In [23]:
#feature5.2 

from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

X_train_minmax = minmax.fit_transform(X_train)

X_test_minmax = minmax.transform(X_test)

In [24]:
print(X_train_minmax[:5])

[[0.22222222 0.55070629 0.83098592 0.         0.         0.
  0.         1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         0.         0.         0.         1.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         1.         1.         0.
  0.         0.         0.        ]
 [0.33333333 0.04233407 0.54929577 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         1.
  0.         1.         0.         0.         0.         1.
  0.         0.         0.        ]
 [0.         0.8086478  0.04225352 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.         1.         0.         0.         0.
  0.         0.         1.         0.         1.         0.
  0.         0.         0.        ]
 [0.22222222 0.36389982 0.38028169 0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.
  1.         0.         1.         0.         0.         0.
  0.         0.         1.         0.         0.         0.
  1.         0.         0.         0.         1.         0.
  0.         0.         0.        ]
 [0.77777778 0.82336412 0.49295775 0.         0.         1.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         1.         0.
  0.         0.         0.         0.         0.         0.
  0.         1.         0.         1.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         1.         0.        ]]

In [25]:
#phase 6 liner regresion 
#feature 6.8
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled,Y_train)
#THE MODEL HAS BEEN TRAINED

LinearRegression()

In [26]:
prediction = model.predict(X_test_scaled)

In [27]:
print(prediction[:5])

[51.29498768 47.31148304 48.18451622 54.96237136 52.29294352]

In [28]:
print(Y_test.iloc[:5])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
Name: Financial Loss (in Million $), dtype: float64

In [29]:
#model evaluation r^2 #feature 6.12 
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, prediction)
print(r2)

-0.006025665291256699

In [30]:
#feature6.13
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(Y_test, prediction)
mean_absolute_error(Y_test,prediction)
print(mae)

24.62073724385283

In [31]:
#feature 6.14 Mean Squared Error (MSE)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, prediction)
print(mse)

813.5061676892593

In [32]:
#feature 6.15 Root Mean Squared Error (RMSE)
import numpy as np
rmse = np.sqrt(mse)
print(rmse)

28.522029515608796

In [33]:
#phase 7 descision tresss
#trainig my first descion tress 
from sklearn.tree import DecisionTreeRegressor
tree= DecisionTreeRegressor(max_depth=5, random_state=42)
tree.fit(X_train,Y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [34]:
#feature 7.12 #predictin using tree 
tree_prediction= tree.predict(X_test)
print(tree_prediction[:10])

[49.46704918 49.46704918 52.29217131 49.46704918 49.46704918 36.31788889
 55.73720779 49.46704918 49.46704918 49.46704918]

In [35]:
print(Y_test.iloc[:10])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
1117    59.67
1411     6.58
2113    80.37
408     70.88
2579    68.83
Name: Financial Loss (in Million $), dtype: float64

In [36]:
#feature 7.13 evaluation of the descion tree 
from sklearn.metrics import r2_score

tree_r2 = r2_score(Y_test, tree_prediction)

print(tree_r2)

-0.07385967070690591

In [37]:
#finding mae 
from sklearn.metrics import mean_absolute_error

tree_mae = mean_absolute_error(Y_test, tree_prediction)

print(tree_mae)

25.253799148800486

In [38]:
#mse 
from sklearn.metrics import mean_squared_error

tree_mse = mean_squared_error(Y_test, tree_prediction)

print(tree_mse)

868.3590245184347

In [39]:
import numpy as np

tree_rmse = np.sqrt(tree_mse)

print(tree_rmse)

29.467932138486315

In [40]:
#feature 7.16 feature importance 
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": tree.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance.head(10))

                                       Feature  Importance
2          Incident Resolution Time (in Hours)    0.284095
1                     Number of Affected Users    0.168885
32  Security Vulnerability Type_Weak Passwords    0.071537
27                             Attack Source_1    0.057581
7                              Country_Germany    0.045378
37             Defense Mechanism Used_Firewall    0.042846
23                          Target Industry_IT    0.040871
20                   Target Industry_Education    0.036311
5                                Country_China    0.034791
8                                Country_India    0.032608

In [41]:
#summary of this phase 
print("========== Decision Tree Results ==========")
print(f"R² Score : {tree_r2:.4f}")
print(f"MAE      : {tree_mae:.4f}")
print(f"MSE      : {tree_mse:.4f}")
print(f"RMSE     : {tree_rmse:.4f}")

========== Decision Tree Results ==========
R² Score : -0.0739
MAE      : 25.2538
MSE      : 868.3590
RMSE     : 29.4679

#phase 8 
Random forest

In [42]:
#feature 8.7 
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(
    random_state=42,
     n_estimators=100,
    max_depth=5
)
forest.fit(X_train, Y_train) #feature 8.8

RandomForestRegressor(max_depth=5, random_state=42)

In [43]:
forest_prediction = forest.predict(X_test)#prediction on unseen data #feature 8.9

In [44]:
print(forest_prediction[:10])

[50.10106893 47.06240526 49.56038238 51.57081413 52.44721898 46.25661513
 49.2369802  48.23701593 50.84885693 52.58258626]

In [45]:
print(Y_test.iloc[:10])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
1117    59.67
1411     6.58
2113    80.37
408     70.88
2579    68.83
Name: Financial Loss (in Million $), dtype: float64

In [46]:
#feature 8.11
#checking R square 
from sklearn.metrics import r2_score

forest_r2 = r2_score(
    Y_test,
    forest_prediction
)

print(forest_r2)

-0.0046586274955005

In [47]:
from sklearn.metrics import mean_absolute_error

forest_mae = mean_absolute_error(
    Y_test,
    forest_prediction
)

print(forest_mae)

24.621652148290202

In [48]:
from sklearn.metrics import mean_squared_error

forest_mse = mean_squared_error(
    Y_test,
    forest_prediction
)

print(forest_mse)

812.4007349784645

In [49]:
import numpy as np

forest_rmse = np.sqrt(forest_mse)

print(forest_rmse)

28.50264435062937

In [50]:
#feature 8.12 feature importance 
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": forest.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance.head(10))

                                       Feature  Importance
1                     Number of Affected Users    0.271236
2          Incident Resolution Time (in Hours)    0.167604
0                                         Year    0.079246
21                  Target Industry_Government    0.021610
8                                Country_India    0.021448
32  Security Vulnerability Type_Weak Passwords    0.019605
13                            Attack Type_DDoS    0.019562
20                   Target Industry_Education    0.019449
7                              Country_Germany    0.019302
27                             Attack Source_1    0.019250

phase 9 KNN

In [51]:
#feature 9.9 kneighborsRegressor 
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(
    n_neighbors=100
)
#feature 9.10 train & predict 
knn.fit(
    X_train_scaled,
    Y_train
)

knn_prediction = knn.predict(
    X_test_scaled
)

In [52]:
print(knn_prediction[:10])

[51.5037 50.1164 49.8906 56.4401 48.738  47.1383 52.9591 51.2588 47.8191
 57.1963]

In [53]:
print(Y_test.iloc[:10])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
1117    59.67
1411     6.58
2113    80.37
408     70.88
2579    68.83
Name: Financial Loss (in Million $), dtype: float64

In [54]:
#feature 9.11 evaluate the KNN model 
from sklearn.metrics import r2_score

knn_r2 = r2_score(Y_test, knn_prediction)

print(knn_r2)

-0.009448707824261326

In [55]:
from sklearn.metrics import mean_absolute_error

knn_mae = mean_absolute_error(
    Y_test,
    knn_prediction
)

print(knn_mae)

24.672337000000002

In [56]:
from sklearn.metrics import mean_squared_error

knn_mse = mean_squared_error(
    Y_test,
    knn_prediction
)

print(knn_mse)

816.2741549374333

In [57]:
import numpy as np

knn_rmse = np.sqrt(knn_mse)

print(knn_rmse)

28.570511982417

In [58]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

knn_r2 = r2_score(Y_test, knn_prediction)
knn_mae = mean_absolute_error(Y_test, knn_prediction)
knn_mse = mean_squared_error(Y_test, knn_prediction)
knn_rmse = np.sqrt(knn_mse)

print("R²   :", knn_r2)
print("MAE  :", knn_mae)
print("MSE  :", knn_mse)
print("RMSE :", knn_rmse)

R²   : -0.009448707824261326
MAE  : 24.672337000000002
MSE  : 816.2741549374333
RMSE : 28.570511982417

In [59]:
#feature 9.14 best value of k 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

rmse_scores = []

for k in range(1, 100):

    model = KNeighborsRegressor(n_neighbors=k)

    model.fit(X_train_scaled, Y_train)

    prediction = model.predict(X_test_scaled)

    rmse = np.sqrt(mean_squared_error(Y_test, prediction))

    rmse_scores.append(rmse)

print(rmse_scores)

[np.float64(39.732234831011795), np.float64(35.10745392422621), np.float64(32.78823804834311), np.float64(32.045820894983066), np.float64(31.39887659381038), np.float64(30.734316687540005), np.float64(30.49899461084101), np.float64(29.935093446114447), np.float64(29.999883596859217), np.float64(29.80791440699936), np.float64(29.778141507404158), np.float64(29.848959519426487), np.float64(29.646246134059247), np.float64(29.590000161920965), np.float64(29.65208457357625), np.float64(29.680546904366803), np.float64(29.603400798570938), np.float64(29.54016080783023), np.float64(29.537753050204202), np.float64(29.477486598009563), np.float64(29.4192620465948), np.float64(29.344390637356142), np.float64(29.28729187228934), np.float64(29.203222939757097), np.float64(29.185519222760682), np.float64(29.235328343943824), np.float64(29.186710960116937), np.float64(29.174855537415077), np.float64(29.176905466510064), np.float64(29.24842021328927), np.float64(29.296082505142383), np.float64(29.21720286710561), np.float64(29.186749268234745), np.float64(29.164764989969093), np.float64(29.158357781589547), np.float64(29.161277459685493), np.float64(29.112929100896398), np.float64(29.12352099148525), np.float64(29.138836914628968), np.float64(29.068921500497456), np.float64(28.99684949059005), np.float64(28.970775287955995), np.float64(28.889773890605884), np.float64(28.83147991124315), np.float64(28.87418265338981), np.float64(28.901090125115587), np.float64(28.868577392523175), np.float64(28.873518943943004), np.float64(28.87528926052051), np.float64(28.878664988012634), np.float64(28.88462913212732), np.float64(28.935842052285945), np.float64(28.935911795406234), np.float64(28.936646027256785), np.float64(28.907392704895425), np.float64(28.89768670949142), np.float64(28.88931178111851), np.float64(28.88487573307423), np.float64(28.880027347473657), np.float64(28.919489373058195), np.float64(28.908176286015152), np.float64(28.91564059156318), np.float64(28.902560943699545), np.float64(28.848701872199015), np.float64(28.82791489440082), np.float64(28.83909326440774), np.float64(28.83752978846788), np.float64(28.8469586598173), np.float64(28.796362024384077), np.float64(28.77571795151725), np.float64(28.775081711090436), np.float64(28.779697277212478), np.float64(28.774845576081134), np.float64(28.766220786831532), np.float64(28.757172133009803), np.float64(28.760235663003616), np.float64(28.748661327479436), np.float64(28.734163413886044), np.float64(28.72998407279821), np.float64(28.689135928217855), np.float64(28.68332556182516), np.float64(28.68004034400492), np.float64(28.6493703856126), np.float64(28.648685071117445), np.float64(28.644363797654233), np.float64(28.63141894646277), np.float64(28.628830672810437), np.float64(28.630824769207948), np.float64(28.633334683876086), np.float64(28.634971891784208), np.float64(28.641405547030605), np.float64(28.637842099563056), np.float64(28.63525621167586), np.float64(28.630479839578634), np.float64(28.632820309308876), np.float64(28.6065915933658), np.float64(28.606652979062503), np.float64(28.592398343844263), np.float64(28.579638889429045)]

phase 10 simple virtual machines

In [60]:
#feature 10.9 
from sklearn.svm import SVR
svr = SVR()
svr.fit(
    X_train_scaled,
    Y_train
)
svr_prediction = svr.predict(
    X_test_scaled
)

In [61]:
print(svr_prediction[:10])

[48.21897535 46.81567415 49.44295322 53.55781887 48.9987691  46.75687317
 52.9484711  49.36455567 47.99269072 54.20637558]

In [62]:
print(Y_test.iloc[:10])

1801    82.04
1190    41.67
1817    88.63
251     89.22
2505    27.38
1117    59.67
1411     6.58
2113    80.37
408     70.88
2579    68.83
Name: Financial Loss (in Million $), dtype: float64

In [63]:
#feature 10.11 evaluation 
from sklearn.metrics import r2_score

svr_r2 = r2_score(
    Y_test,
    svr_prediction
)

print(svr_r2)

-0.004708287118518006

In [64]:
from sklearn.metrics import mean_absolute_error

svr_mae = mean_absolute_error(
    Y_test,
    svr_prediction
)

print(svr_mae)

24.63040775343002

In [65]:
from sklearn.metrics import mean_squared_error

svr_mse = mean_squared_error(
    Y_test,
    svr_prediction
)

print(svr_mse)

812.4408914188057

In [66]:
import numpy as np

svr_rmse = np.sqrt(svr_mse)

print(svr_rmse)

28.503348775517686

In [67]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

print("R²   :", r2_score(Y_test, svr_prediction))
print("MAE  :", mean_absolute_error(Y_test, svr_prediction))
print("MSE  :", mean_squared_error(Y_test, svr_prediction))
print("RMSE :", np.sqrt(mean_squared_error(Y_test, svr_prediction)))

R²   : -0.004708287118518006
MAE  : 24.63040775343002
MSE  : 812.4408914188057
RMSE : 28.503348775517686